name: algorithm_weekly_alarm

on:
schedule: - cron: "0 9 \* \* 5"

jobs:
algo_daily_alarm:
runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: POST Algorithm repo weekly alarm to Slack
        shell: bash
        run:
        # 올해 년도 구하기
          NOW_YEAR=$(date +%Y)
          TARGET_FILE_PATH="problems"

        # 올해 알고리즘 문제를 기록하는 폴더를 모두 찾아 배열에 넣기
          TARGET_DIR=($(find ${TARGET_FILE_PATH} -type d | grep ${NOW_YEAR} | cut -c 38- | sort))

          TARGET_VALUE=()
          LENGTH=0
          TOTAL=0

        # 반복문을 이용해 올해 알고리즘 문제 폴더를 순회하면서 폴더당 문제 개수, 문제 개수 총합 구하기
          for dir in "${TARGET_DIR[@]}"
          do
              LENGTH=$(($LENGTH + 1))
              VALUE=$(ls -al "${TARGET_FILE_PATH}/$dir" | grep -E "^-.*\.py$|^-.*\.js" | wc -l | sed 's/ //g')
              TARGET_VALUE+=( $VALUE )
              TOTAL=$(( $TOTAL + $VALUE ))
          done

          echo $LENGTH
          NOW_DATE=$(date +%Y.%m.%d)
          MESSAGE="*주간 알고리즘 결산($NOW_DATE)*\n\n"

        # 메시지에 매달 푼 문제 개수 정보 추가하기
          for ((i=0;i<$LENGTH;i++)); do
              MESSAGE+="$(echo ${TARGET_DIR[$i]} | cut -c -4)년 $(echo ${TARGET_DIR[$i]} | cut -c 5-)월에 푼 문제 수: ${TARGET_VALUE[$i]}\n"
          done

          MESSAGE+="--------------------------------\n${NOW_YEAR}년에 푼 문제\n*총합 $TOTAL 문제 입니다"

        # 채널로 메시지 보내기
          curl -X POST --data-urlencode "payload={\"channel\": \"#알고_알리미\", \"username\": \"알고 알리미\", \"text\": \"${MESSAGE}\", \"icon_emoji\": \":male-technologist:\"}"${{ secrets.SLACK_URL }}
